tabWidth: 4
useTabs: false
semi: false
trailingComma: none
bracketSpacing: true
bracketSameLine: false
arrowParens: always
proseWrap: never
endOfLine: crlf
embeddedLanguageFormatting: auto
printWidth: 80
singleQuote: true
experimentalTernaries: true
quoteProps: as-needed
vueIndentScriptAndStyle: true
